version: '3.8'

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_vol:/var/lib/mysql

  app:
    build: .
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - /
    ports:
      - "3000:3000"
    depends_on:
      - db
  front:
    build:
      context: ./frontend
      dockerfile: DockerFile
    volumes:
      - /frontend
    command: sh -c "cd frontend && npm start"
    ports:
      - "8000:3001"
volumes:
  mysql_vol:
