FROM ruby:3.0.2
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /mogumoguDocekr
WORKDIR /mogumoguDocekr
ADD Gemfile /mogumoguDocekr/Gemfile
ADD Gemfile.lock /mogumoguDocekr/Gemfile.lock
RUN bundle install
ADD . /mogumoguDocekr
